### ISSUE TITLE
crash when trying to re-connect

### ISSUE THREAD

**Issue by muelli** [flathub/org.remmina.Remmina#26]
excuse my ignorance for posting here rather than remmina upstream. I hope you can forward the report accordingly.

I got a crash. It's the third time it has happened, so I guess it's quite reproducible. I connect to a RDP server. Then I suspend. Resume. I try to connect again. It crashes:

```
Thread 1 "remmina" received signal SIGSEGV, Segmentation fault.
0x00007ffff236ac1b in remmina_rdp_open_connection (gp=<optimized out>)
    at plugins/rdp/rdp_plugin.c:1794
1794		while((c = *p) != 0 && nthname < sizeof(thname) - 1 ) {
(gdb) bt
#0  0x00007ffff236ac1b in remmina_rdp_open_connection (gp=<optimized out>)
    at plugins/rdp/rdp_plugin.c:1794
#1  0x0000555555597da2 in remmina_protocol_widget_open_connection_real
    (data=<optimized out>) at src/remmina_protocol_widget.c:289
#2  0x0000555555597f5e in remmina_protocol_widget_open_connection
    (gp=<optimized out>) at src/remmina_protocol_widget.c:324
#3  0x00005555555aeff5 in open_connection_last_stage (user_data=0x555555d451a0)
    at src/rcw.c:3989
#4  0x00007ffff76667c8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7665c2e in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7665fe0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7666083 in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7514e95 in g_application_run ()
    at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x000055555557adc5 in main (argc=1, argv=0x7fffffffdbd8)
    at src/remmina.c:355
(gdb) 
```

and `t a a bt full`:
```
gdb) t a a bt full

Thread 23 (LWP 30):
#0  0x00007ffff723dd05 in pthread_cond_wait () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055555558ce2b in remmina_masterthread_exec_and_wait (d=0x7fffd46d6d00) at src/remmina_masterthread_exec.c:132
        __clframe = {__cancel_routine = <optimized out>, __cancel_arg = 0x7fffd46d6d00, __do_it = 1, __cancel_type = <optimized out>}
#2  0x000055555557e156 in remmina_file_get_string (remminafile=0x55555592f710, setting=setting@entry=0x5555555b6dec "server") at src/remmina_file.c:466
        d = 0x7fffd46d6d00
        retval = <optimized out>
        value = <optimized out>
#3  0x0000555555598dae in remmina_protocol_widget_start_direct_tunnel (gp=0x555555d451a0, default_port=3389, port_plus=0) at src/remmina_protocol_widget.c:828
        server = <optimized out>
        ssh_tunnel_server = <optimized out>
        ssh_tunnel_host = 0x555555d451b0 "\300]\320UUU"
        srv_host = 0x7fffffffd82f ""
        dest = <optimized out>
        srv_port = -231256064
        ssh_tunnel_port = 32767
        msg = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        mp = <optimized out>
        tunnel = <optimized out>
        __func__ = "remmina_protocol_widget_start_direct_tunnel"
#4  0x00007ffff23698bd in remmina_rdp_tunnel_init (gp=gp@entry=0x555555d451a0) at plugins/rdp/rdp_plugin.c:194
        hostport = <optimized out>
        s = <optimized out>
        host = 0x7ffff2375000 "plugin-data"
        cert_host = <optimized out>
        cert_port = <optimized out>
        port = 0
        rfi = 0x555555d44590
        __func__ = "remmina_rdp_tunnel_init"
#5  0x00007ffff236b0fa in remmina_rdp_main (gp=0x555555d451a0) at plugins/rdp/rdp_plugin.c:1018
        sm = <optimized out>
        rdpsnd_rate = <optimized out>
        cs = <optimized out>
        gateway_host = 0x0
        proxy_password = <optimized out>
        rdpsnd_param1 = "\020\016\001\324\377\177\000\000\257\302\377\323\377\177\000"
        desktopScaleFactor = 0
--Type <RET> for more, q to quit, c to continue without paging--
        deviceScaleFactor = 0
        proxy_username = <optimized out>
        proxy_hostname = <optimized out>
        proxy_port = <optimized out>
        s = <optimized out>
        rdpsnd_params = {0x0, 0x0, 0x0}
        rdpsnd_param2 = "\000\311\377\322\377\177\000\000\316i\021\362\377\177\000"
        remminafile = 0x55555592f710
        gateway_port = 0
        desktopOrientation = 0
        orphaned = <optimized out>
        value = <optimized out>
        rdpsnd_nparams = <optimized out>
        channels = 0x555555d54970
        rdpsnd_channel = <optimized out>
        rfi = 0x555555d44590
        proxy_type = <optimized out>
        __func__ = "remmina_rdp_main"
        gp = 0x555555d451a0
        rfi = 0x555555d44590
#6  0x00007ffff236b0fa in remmina_rdp_main_thread (data=0x555555d451a0) at plugins/rdp/rdp_plugin.c:1721
--Type <RET> for more, q to quit, c to continue without paging--
        gp = 0x555555d451a0
        rfi = 0x555555d44590
#7  0x00007ffff72375e2 in  () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff6ada413 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 3 (LWP 10):
#0  0x00007ffff6acf8ef in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7665f4e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff76662d3 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7550c7a in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff768f751 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff72375e2 in  () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff6ada413 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (LWP 9):
#0  0x00007ffff6acf8ef in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7665f4e in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7666083 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff76660d1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff768f751 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff72375e2 in  () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#6  0x00007ffff6ada413 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 1 (LWP 5):
#0  0x00007ffff236ac1b in remmina_rdp_open_connection (gp=<optimized out>) at plugins/rdp/rdp_plugin.c:1794
        rfi = 0x555555d44590
        remminafile = 0x55555592f710
        profile_name = 0x0
        p = 0x0
        thname = "RemmRDP:\000b\246\366\377\177\000"
        c = <optimized out>
        nthname = 8
#1  0x0000555555597da2 in remmina_protocol_widget_open_connection_real (data=<optimized out>) at src/remmina_protocol_widget.c:289
        gp = 0x555555d451a0
        plugin = 0x7ffff237c260 <remmina_rdp>
        feature = <optimized out>
        num_plugin = <optimized out>
        num_ssh = <optimized out>
#2  0x0000555555597f5e in remmina_protocol_widget_open_connection (gp=<optimized out>) at src/remmina_protocol_widget.c:324
        s = <optimized out>
        name = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        mp = <optimized out>
#3  0x00005555555aeff5 in open_connection_last_stage (user_data=0x555555d451a0) at src/rcw.c:3989
        gp = 0x555555d451a0
#4  0x00007ffff76667c8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7665c2e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff7665fe0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff7666083 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff7514e95 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x000055555557adc5 in main (argc=1, argv=0x7fffffffdbd8) at src/remmina.c:355
        app = 0x5555557050f0
        app_id = <optimized out>
        status = <optimized out>
(gdb)
```

I hope I don't leak credentials now...

**Comment by antenore** [comment]
Thanks for reporting this!
