### ISSUE TITLE
Remmina crashing on exit on Fedora 30

### ISSUE THREAD

**Issue by neildick** [flathub/org.remmina.Remmina#7]
Hi, I'm not sure if this is the correct place to report this issue.
Host: Fedora 30 with Gnome & Wayland
Issue: Remmina installed from Flathub crashes when closing the application with a kernel oops.
`flatpak update` reports everything up to date. 

dmesg output:
```
[ 1442.891183] traps: remmina[6301] general protection fault ip:7fc67c9cf5ad sp:7ffc0d8d2220 error:0 in libgobject-2.0.so.0.6000.0[7fc67c9a3000+34000]
```
journalctl output:
```
May 07 06:30:50 ceres polkitd[1340]: Registered Authentication Agent for unix-process:6036:8632194 (system bus name :1.739 [flatpak info org.remmina.Remmina], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8)
May 07 06:30:50 ceres polkitd[1340]: Unregistered Authentication Agent for unix-process:6036:8632194 (system bus name :1.739, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8)
May 07 06:31:55 ceres polkitd[1340]: Registered Authentication Agent for unix-process:6125:8638714 (system bus name :1.753 [flatpak search remmina], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8)
May 07 06:31:58 ceres polkitd[1340]: Registered Authentication Agent for unix-process:6261:8639036 (system bus name :1.775 [/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/remmina org.remmina.Remmina], object path /o>
May 07 06:31:58 ceres flatpak-system-helper[4625]: system: Pulled appstream2/x86_64 from /var/tmp/flatpak-cache-Q1FN1Z/repo-kERIBM
May 07 06:31:58 ceres polkitd[1340]: Unregistered Authentication Agent for unix-process:6261:8639036 (system bus name :1.775, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8) (disconnected from bus)
May 07 06:31:59 ceres polkitd[1340]: Unregistered Authentication Agent for unix-process:6125:8638714 (system bus name :1.753, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8)
May 07 06:33:39 ceres audit[6301]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=6301 comm="remmina" exe="/app/bin/remmina" sig=11 res=1
May 07 06:33:39 ceres kernel: traps: remmina[6301] general protection fault ip:7fc67c9cf5ad sp:7ffc0d8d2220 error:0 in libgobject-2.0.so.0.6000.0[7fc67c9a3000+34000]
May 07 06:33:39 ceres systemd[1]: Started Process Core Dump (PID 6384/UID 0).
May 07 06:33:39 ceres audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-6384-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=s>
May 07 06:33:39 ceres systemd[1]: systemd-coredump@2-6384-0.service: Succeeded.
May 07 06:33:39 ceres audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@2-6384-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=su>
May 07 06:33:39 ceres abrt-server[6396]: Unsupported container technology
May 07 06:33:39 ceres abrt-server[6396]: Lock file '.lock' was locked by process 6399, but it crashed?
May 07 06:33:39 ceres abrt-server[6396]: Error: No segments found in coredump './coredump'
May 07 06:33:40 ceres abrt-server[6396]: Can't open file 'core_backtrace' for reading: No such file or directory
May 07 06:33:40 ceres abrt-server[6396]: Lock file '.lock' is locked by process 2650
May 07 06:33:40 ceres abrt-dump-journal-oops[1359]: abrt-dump-journal-oops: Found oopses: 1
May 07 06:33:40 ceres abrt-dump-journal-oops[1359]: abrt-dump-journal-oops: Creating problem directories
May 07 06:33:40 ceres abrt-notification[6433]: Process 6301 (remmina) crashed in ??()
May 07 06:33:41 ceres abrt-server[6432]: Can't find a meaningful backtrace for hashing in '.'
May 07 06:33:41 ceres abrt-server[6432]: Option 'DropNotReportableOopses' is not configured
May 07 06:33:41 ceres abrt-server[6432]: Preserving oops '.' because DropNotReportableOopses is 'no'
May 07 06:33:41 ceres abrt-notification[6451]: System encountered a non-fatal error in ??()
May 07 06:33:41 ceres abrt-dump-journal-oops[1359]: Reported 1 kernel oopses to Abrt
```

Thanks

**Comment by larchunix** [comment]
The segfault seems to occur only when Remmina is quitted by clicking on the cross button of the window decoration.

When Remmina is quitted using the Quit menu item, the segfault does not occur.

**Comment by larchunix** [comment]
Backtrace:

```
Thread 4 (Thread 0x7f85e7976700 (LWP 17)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f85f14f663e in g_cond_wait_until (cond=cond@entry=0x55a928d58068, mutex=mutex@entry=0x55a928d58060, end_time=end_time@entry=660802726)
    at ../glib/gthread-posix.c:1460
        now = {tv_sec = 645, tv_nsec = 802727403}
        span = {tv_sec = 14, tv_nsec = 999998597}
        sampled = 0
        res = <optimized out>
#2  0x00007f85f147b021 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0x55a928d58060, wait=wait@entry=1, end_time=end_time@entry=660802726)
    at ../glib/gasyncqueue.c:422
        retval = <optimized out>
        __FUNCTION__ = "g_async_queue_pop_intern_unlocked"
#3  0x00007f85f147b615 in g_async_queue_timeout_pop (queue=0x55a928d58060, timeout=timeout@entry=15000000) at ../glib/gasyncqueue.c:545
        end_time = 660802726
        retval = <optimized out>
        __FUNCTION__ = "g_async_queue_timeout_pop"
#4  0x00007f85f14d4801 in g_thread_pool_wait_for_new_pool () at ../glib/gthreadpool.c:168
        pool = <optimized out>
        local_max_idle_time = 15000
        local_wakeup_thread_serial = <optimized out>
        local_max_unused_threads = <optimized out>
        last_wakeup_thread_serial = 0
        have_relayed_thread_marker = <optimized out>
        pool = <optimized out>
        local_wakeup_thread_serial = <optimized out>
        local_max_unused_threads = <optimized out>
        local_max_idle_time = <optimized out>
        last_wakeup_thread_serial = <optimized out>
        have_relayed_thread_marker = <optimized out>
#5  g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/gthreadpool.c:365
        free_pool = <optimized out>
        task = <optimized out>
        pool = <optimized out>
#6  0x00007f85f14d3d41 in g_thread_proxy (data=0x55a928ec8b70) at ../glib/gthread.c:805
        thread = 0x55a928ec8b70
        __FUNCTION__ = "g_thread_proxy"
        _g_boolean_var_ = <optimized out>
#7  0x00007f85f1092132 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140213092837120, 2111193597004144139, 140733513828750, 140733513828751, 140213092837120, 94185023175840, 
                -2141540467055862261, -2141578762977223157}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
#8  0x00007f85f099c093 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f85eec5f700 (LWP 15)):
#0  0x00007f85f0990e91 in __GI___poll (fds=0x55a928d992f0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f85f14aa2c6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x55a928d992f0, timeout=<optimized out>, context=0x55a928dcc3a0)
    at ../glib/gmain.c:4228
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7f85f14b9f40 <g_poll>
        poll_func = <optimized out>
        ret = <optimized out>
        errsv = <optimized out>
#2  g_main_context_iterate (context=context@entry=0x55a928dcc3a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:3922
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x55a928d992f0
#3  0x00007f85f14aa3f0 in g_main_context_iteration (context=0x55a928dcc3a0, may_block=may_block@entry=1) at ../glib/gmain.c:3988
        retval = <optimized out>
#4  0x00007f85f14aa441 in glib_worker_main (data=<optimized out>) at ../glib/gmain.c:5868
No locals.
#5  0x00007f85f14d3d41 in g_thread_proxy (data=0x55a928dc9c50) at ../glib/gthread.c:805
        thread = 0x55a928dc9c50
        __FUNCTION__ = "g_thread_proxy"
        _g_boolean_var_ = <optimized out>
#6  0x00007f85f1092132 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140213213329152, 2111193597004144139, 140733513831006, 140733513831007, 140213213329152, 0, 
                -2141555151012176373, -2141578762977223157}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007f85f099c093 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f85ee45e700 (LWP 16)):
#0  0x00007f85f0990e91 in __GI___poll (fds=0x55a928de1820, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f85f14aa2c6 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x55a928de1820, timeout=<optimized out>, context=0x55a928ddcb40)
    at ../glib/gmain.c:4228
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7f85f14b9f40 <g_poll>
        poll_func = <optimized out>
        ret = <optimized out>
        errsv = <optimized out>
#2  g_main_context_iterate (context=0x55a928ddcb40, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3922
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x55a928de1820
#3  0x00007f85f14aa682 in g_main_loop_run (loop=0x55a928ddcc30) at ../glib/gmain.c:4123
        self = <optimized out>
        __FUNCTION__ = "g_main_loop_run"
#4  0x00007f85f139b39a in gdbus_shared_thread_func (user_data=0x55a928ddcb10) at ../gio/gdbusprivate.c:275
        data = 0x55a928ddcb10
#5  0x00007f85f14d3d41 in g_thread_proxy (data=0x55a928dc9cf0) at ../glib/gthread.c:805
        thread = 0x55a928dc9cf0
        __FUNCTION__ = "g_thread_proxy"
        _g_boolean_var_ = <optimized out>
#6  0x00007f85f1092132 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140213204936448, 2111193597004144139, 140733513831422, 140733513831423, 140213204936448, 94185023458064, 
                -2141554052037419509, -2141578762977223157}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
#7  0x00007f85f099c093 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f85eefc8c00 (LWP 14)):
#0  g_type_check_instance (type_instance=type_instance@entry=0x55a9290c8b50) at ../gobject/gtype.c:4131
        node = <optimized out>
#1  0x00007f85f1253188 in g_signal_handlers_disconnect_matched (instance=0x55a9290c8b50, mask=mask@entry=(G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA), 
    signal_id=signal_id@entry=0, detail=detail@entry=0, closure=closure@entry=0x0, func=func@entry=0x7f85f18e4970 <menu_deactivate_cb>, data=0x55a928df6660)
    at ../gobject/gsignal.c:2931
        _g_boolean_var_ = <optimized out>
        n_handlers = 0
        __FUNCTION__ = "g_signal_handlers_disconnect_matched"
#2  0x00007f85f18e4c94 in gtk_menu_button_dispose (object=0x55a928df6660) at gtkmenubutton.c:1043
        priv = 0x55a928df6480
#3  0x00007f85f123e7d0 in g_object_run_dispose (object=0x55a928df6660) at ../gobject/gobject.c:1108
        __FUNCTION__ = "g_object_run_dispose"
#4  0x00007f85f1897a75 in gtk_header_bar_forall (container=<optimized out>, include_internals=0, callback=0x7f85f1a1aca0 <gtk_widget_destroy>, 
    callback_data=0x0) at gtkheaderbar.c:1760
        bar = <optimized out>
        priv = 0x55a928def230
        child = <optimized out>
        children = 0x55a928f7af60
#5  0x00007f85f180798a in gtk_container_destroy (widget=0x55a928def3e0) at gtkcontainer.c:1701
        container = 0x55a928def3e0
        priv = 0x55a928def2d0
#6  0x00007f85f1237695 in g_closure_invoke (closure=0x55a928e34ec0, return_value=0x0, n_param_values=1, param_values=0x7fff13198dd0, 
    invocation_hint=0x7fff13198d50) at ../gobject/gclosure.c:810
        marshal = 0x7f85f1235c60 <g_type_class_meta_marshal>
        marshal_data = 0x98
        in_marshal = 1
        real_closure = 0x55a928e34ea0
        __FUNCTION__ = "g_closure_invoke"
#7  0x00007f85f124bc06 in signal_emit_unlocked_R (node=node@entry=0x55a928e37990, detail=detail@entry=0, instance=instance@entry=0x55a928def3e0, 
    emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fff13198dd0) at ../gobject/gsignal.c:3549
        need_unset = 0
        accumulator = 0x0
        emission = {next = 0x7fff131991e0, instance = 0x55a928def3e0, ihint = {signal_id = 64, detail = 0, run_type = G_SIGNAL_RUN_CLEANUP}, 
          state = EMISSION_STOP, chain_type = 94185024331456}
        class_closure = 0x55a928e34ec0
        hlist = <optimized out>
        handler_list = 0x0
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {
              v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 64
        max_sequential_handler_number = 1973
        return_value_altered = <optimized out>
#8  0x00007f85f1254bbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, 
    var_args=var_args@entry=0x7fff13198f80) at ../gobject/gsignal.c:3391
        instance_and_params = 0x7fff13198dd0
        signal_return_type = <optimized out>
        param_values = 0x7fff13198de8
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ = "g_signal_emit_valist"
#9  0x00007f85f1255273 in g_signal_emit (instance=instance@entry=0x55a928def3e0, signal_id=<optimized out>, detail=detail@entry=0)
    at ../gobject/gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fff13199060, reg_save_area = 0x7fff13198fa0}}
#10 0x00007f85f1a234cc in gtk_widget_dispose (object=0x55a928def3e0) at gtkwidget.c:12098
        widget = 0x55a928def3e0
        priv = 0x55a928def2f0
        sizegroups = <optimized out>
#11 0x00007f85f123e7d0 in g_object_run_dispose (object=0x55a928def3e0) at ../gobject/gobject.c:1108
        __FUNCTION__ = "g_object_run_dispose"
#12 0x00007f85f180798a in gtk_container_destroy (widget=0x55a928e00d00) at gtkcontainer.c:1701
        container = 0x55a928e00d00
        priv = 0x55a928e00bf0
#13 0x00007f85f123777d in g_closure_invoke (closure=0x55a928e34ec0, return_value=0x0, n_param_values=1, param_values=0x7fff13199270, invocation_hint=0x7fff131991f0) at ../gobject/gclosure.c:810
        marshal = 0x7f85f1235c60 <g_type_class_meta_marshal>
        marshal_data = 0x98
        in_marshal = 0
        real_closure = 0x55a928e34ea0
        __FUNCTION__ = "g_closure_invoke"
#14 0x00007f85f124bc06 in signal_emit_unlocked_R (node=node@entry=0x55a928e37990, detail=detail@entry=0, instance=instance@entry=0x55a928e00d00, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fff13199270) at ../gobject/gsignal.c:3549
        need_unset = 0
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x55a928e00d00, ihint = {signal_id = 64, detail = 0, run_type = G_SIGNAL_RUN_CLEANUP}, state = EMISSION_STOP, chain_type = 94185023163088}
        class_closure = 0x55a928e34ec0
        hlist = <optimized out>
        handler_list = 0x55a929223ac0
        return_accu = 0x0
        accu = {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        signal_id = 64
        max_sequential_handler_number = 1966
        return_value_altered = <optimized out>
#15 0x00007f85f1254bbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff13199420) at ../gobject/gsignal.c:3391
        instance_and_params = 0x7fff13199270
        signal_return_type = <optimized out>
        param_values = 0x7fff13199288
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __FUNCTION__ = "g_signal_emit_valist"
#16 0x00007f85f1255273 in g_signal_emit (instance=instance@entry=0x55a928e00d00, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fff13199500, reg_save_area = 0x7fff13199440}}
#17 0x00007f85f1a234cc in gtk_widget_dispose (object=0x55a928e00d00) at gtkwidget.c:12098
        widget = 0x55a928e00d00
        priv = 0x55a928e00c10
        sizegroups = <optimized out>
#18 0x00007f85f1a36b1c in gtk_window_dispose (object=0x55a928e00d00) at gtkwindow.c:3164
        window = 0x55a928e00d00
        priv = 0x55a928e00aa0
#19 0x00007f85f123e7d0 in g_object_run_dispose (object=0x55a928e00d00) at ../gobject/gobject.c:1108
        __FUNCTION__ = "g_object_run_dispose"
#20 0x00007f85f1a1ad09 in gtk_widget_destroy (widget=<optimized out>) at gtkwidget.c:4728
        __FUNCTION__ = "gtk_widget_destroy"
#21 0x00007f85f18d87a8 in gtk_main_do_event (event=0x55a92918b9e0) at gtkmain.c:1831
        grab_widget = <optimized out>
        window_group = 0x55a9292cf8a0
        rewritten_event = <optimized out>
        device = 0x0
        tmp_list = <optimized out>
        event_widget = 0x55a928e00d00
        topmost_widget = <optimized out>
        event_widget = <optimized out>
        grab_widget = <optimized out>
        topmost_widget = <optimized out>
        window_group = <optimized out>
        rewritten_event = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        __FUNCTION__ = "gtk_main_do_event"
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        window = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        mnemonics_visible = <optimized out>
        window = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
#22 gtk_main_do_event (event=event@entry=0x55a92918b9e0) at gtkmain.c:1685
        event_widget = <optimized out>
        window_group = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        __FUNCTION__ = "gtk_main_do_event"
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        window = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
        mnemonics_visible = <optimized out>
        window = <optimized out>
        __inst = <optimized out>
        __t = <optimized out>
        __r = <optimized out>
#23 0x00007f85f1a30835 in send_delete_event (data=0x55a928e00d00) at gtkwindow.c:1331
        window = 0x55a928e00d00
        priv = 0x55a928e00aa0
        event = 0x55a92918b9e0
#24 0x00007f85f15afe9c in gdk_threads_dispatch (data=0x55a928f8a500) at gdk.c:772
        dispatch = 0x55a928f8a500
        ret = 0
#25 0x00007f85f14a9f68 in g_main_dispatch (context=0x55a928d99920) at ../glib/gmain.c:3189
        dispatch = 0x7f85f14a67a0 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x55a928f8a500
        callback = 0x7f85f15afe70 <gdk_threads_dispatch>
        cb_funcs = <optimized out>
        cb_data = 0x55a92927d220
        need_destroy = <optimized out>
        source = 0x55a929262a50
        current = 0x55a928ddd2d0
        i = 0
        current = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "g_main_dispatch"
        source = <optimized out>
        _g_boolean_var_ = <optimized out>
        was_in_call = <optimized out>
        user_data = <optimized out>
        callback = <optimized out>
        cb_funcs = <optimized out>
        cb_data = <optimized out>
        need_destroy = <optimized out>
        dispatch = <optimized out>
        prev_source = <optimized out>
        _g_boolean_var_ = <optimized out>
#26 g_main_context_dispatch (context=context@entry=0x55a928d99920) at ../glib/gmain.c:3854
No locals.
#27 0x00007f85f14aa358 in g_main_context_iterate (context=context@entry=0x55a928d99920, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:3927
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x55a928ff03c0
#28 0x00007f85f14aa3f0 in g_main_context_iteration (context=context@entry=0x55a928d99920, may_block=may_block@entry=1) at ../glib/gmain.c:3988
        retval = <optimized out>
#29 0x00007f85f136009d in g_application_run (application=0x55a928d961a0, argc=<optimized out>, argv=0x7fff13199898) at ../gio/gapplication.c:2516
        arguments = 0x55a928d998e0
        status = 0
        context = 0x55a928d99920
        acquired_context = 1
        __FUNCTION__ = "g_application_run"
#30 0x000055a927f45639 in main (argc=1, argv=0x7fff13199898) at src/remmina.c:310
        app = 0x55a928d961a0
        app_id = <optimized out>
        status = <optimized out>
```

**Comment by antenore** [comment]
Thanks for the trace, unfortunately it doesn't say too much to me.
Did you get it on Arch Linux or another distro? Because it doesn't happen to me.

@giox069 any clues?

**Comment by antenore** [comment]
Well, I don't have wayland BTW, so it maybe a bug in the Gnome/wayland stack, it's something that should be reported to the freedesktop or gnome project, or wait the next updates to see if it goeas away :-P

Let's see if @giox069  has anything to say...

**Comment by larchunix** [comment]
I managed to reproduce the issue both on Fedora and ArchLinux but only with Flatpaked Remmina not with the version packaged by the distribution.

I don't use Wayland either.

**Comment by neildick** [comment]
It seems to happen for me on Gnome/Wayland and Gnome/X11 so I don't think it's Waylands fault.

**Comment by antenore** [comment]
We are debugging

**Comment by antenore** [comment]
Have been fixed in the master branch... 
@larchunix in few days (hopefully) we will release a bug fixing version, do we wait to update the flatpak or do we add the commit hash?

**Comment by larchunix** [comment]
Since it doesn't prevent Remmina to function properly, I would prefer to wait until the next release.

**Comment by neildick** [comment]
Fixed in the latest update. Thanks guys!
